
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce_3
        username: springstudent
        password: springstudent

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
